### ISSUE TITLE
Missing dependency for IndexedPersistentCacheStore?

### ISSUE THREAD

**Issue by cpmcdaniel** [httpcache4j/httpcache4j#44]
I can use PersistentCacheStore and FilePersistentCacheStore (though I found a separate issue with this one), but if I try to use IndexedPersistentCacheStore:

java.lang.ClassNotFoundException: com.google.common.cache.RemovalListener

**Comment by hamnis** [comment]
guava is an optional dependency, so if you need to use the IndexedPersistentCacheStore you need to add the guava dependency yourself. This should probably be documented.

**Comment by cpmcdaniel** [comment]
PR: https://github.com/httpcache4j/httpcache4j/pull/46

**Comment by cpmcdaniel** [comment]
Also, it would be nice to have a rationale in the docstring for each of the CacheStorage implementation, so we can make informed decisions on which one to choose (also mentioned in the PR).

**Comment by hamnis** [comment]
Thanks for the PR.

**Comment by hamnis** [comment]
Deprecated the IndexedPersistentCacheStore. Will move this into own repo if desired. Doc changes released as 5.0.0-M3
