### ISSUE TITLE
Exception when receiving cached payload without content-type

### ISSUE THREAD

**Issue by maggikpunkt** [httpcache4j/httpcache4j#56]
When files are stored in cache and the server does not send a content-type the headers are stored without content-type: `headers=Accept-Ranges\: bytes\r\nLast-Modified\: Mon, 12 May 2014 20\:06\:46 GMT\r\nContent-Length\: 21284\r\nServer\: Jetty(9.2.13.v20150730)`

When loading we get an exception:

```
 java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at org.codehaus.httpcache4j.cache.SerializableCacheItem.parse(SerializableCacheItem.java:79)
	at org.codehaus.httpcache4j.cache.FilePersistentCacheStorage.readItem(FilePersistentCacheStorage.java:106)
	at org.codehaus.httpcache4j.cache.FilePersistentCacheStorage.lambda$getItem$0(FilePersistentCacheStorage.java:145)
```
SerializableCacheItem.parse(Properties object) does `headers.getContentType().get()` without checking for presence. I would change it to `orElse(MIMEType.APPLICATION_OCTET_STREAM)` but I am not really aware of the implications this would have.

**Comment by hamnis** [comment]
Hi.
Thanks for the bug report. Nice find!

According to the https://tools.ietf.org/html/rfc7231#section-3.1.1.5 it should be safe to assume 
MIMEType.APPLICATION_OCTET_STREAM

so will you provide a pull request with that small change? Please also add a test

**Comment by hamnis** [comment]
`Optional.get` is always a code smell, I'll open a separate issue for that.
